### ISSUE TITLE
Hotkeys naar tabbladen, modal nieuw aanw/kind

### ISSUE THREAD

**Issue by jokkebrok** [FKint/JokkebrokAdministratie#23]
Hotkeys, suggesties:
D: ga naar tabblad Dashboard  (werkt enkel als er geen modals open staan)
A: ga naar tabblad Aanwezig (werkt enkel als er geen modals open staan)
K: ga naar tabblad Kinderen (werkt enkel als er geen modals open staan)
U: ga naar tabblad Uitstappen (werkt enkel als er geen modals open staan)

Wanneer op tabblad Aanwezig, hotkey N: open modal voor nieuwe Aanwezigheid registeren.
Wanneer op tabblad Kinderen, hotkey N: open modal voor nieuw Kind registeren.

**Comment by FKint** [comment]
Is dit zeker de moeite? Zullen die hotkeys gebruikt worden?

**Comment by FKint** [comment]
f5dff545ae9a5489a41c49b51b09ce6bd663be1c
