### ISSUE TITLE
Bug NULL voogd

### ISSUE THREAD

**Issue by RDEMOL** [FKint/JokkebrokAdministratie#31]
Bug descr:
Na verwijderen van alle voogden in een kind view, is dit kind niet meer vindbaar dmv filters in de kind-lijst. Spinner blijft draaien.

How to reproduce
Stap 1 (Nieuw kind, definieer geen voogd, opslaan)
![image](https://cloud.githubusercontent.com/assets/1383142/5789285/82f1d90a-9e64-11e4-9ded-9949ac52c782.png)
Stap 2 (Wijzig net opgeslagen kind)
![image](https://cloud.githubusercontent.com/assets/1383142/5789288/8c38edfa-9e64-11e4-8f64-b29d5e594c42.png)
Stap 3 (Verwijder alle voogden; opslaan)
![image](https://cloud.githubusercontent.com/assets/1383142/5789290/91628c6e-9e64-11e4-8ff2-445b4208235f.png)

**Comment by jokkebrok** [comment]
Alternatieve methode voor bug reproduce:

Stap 1: filter kind-lijst op "fietsen"
![image](https://cloud.githubusercontent.com/assets/1383142/5789321/56525db4-9e66-11e4-8b20-9bec6ee31b70.png)
Stap 2: maak kind (naam = fietsen) + OPSLAAN
![image](https://cloud.githubusercontent.com/assets/1383142/5789323/646c2114-9e66-11e4-9d5e-89c33bf9c83c.png)
Stap 3: kind uit stap 2 + WIJZIGEN
![image](https://cloud.githubusercontent.com/assets/1383142/5789324/77b89248-9e66-11e4-942b-1edf1041b960.png)
Stap 4: geen velden aanpassen, geen knopjes drukken + OPSLAAN
![image](https://cloud.githubusercontent.com/assets/1383142/5789327/8b87be20-9e66-11e4-947b-c14e92a617ce.png)
Stap 5: spinner
![image](https://cloud.githubusercontent.com/assets/1383142/5789330/a4b01988-9e66-11e4-824a-6abd8a596aaa.png)
