### ISSUE TITLE
Kind wijzigen, maakt nieuwe instantie van identieke Kind

### ISSUE THREAD

**Issue by RDEMOL** [FKint/JokkebrokAdministratie#35]
![image](https://cloud.githubusercontent.com/assets/1383142/5841454/67b1d37a-a19d-11e4-9696-ff7934c245d6.png)
![image](https://cloud.githubusercontent.com/assets/1383142/5841456/6bd1ceec-a19d-11e4-9d77-e1f3d300475e.png)
![image](https://cloud.githubusercontent.com/assets/1383142/5841458/6f20186a-a19d-11e4-8990-be0b10a8a3d0.png)

**Comment by FKint** [comment]
1eaafa200ba6667d7f2db48b1e656367eac50878
