### ISSUE TITLE
Duplicate voogd

### ISSUE THREAD

**Issue by RDEMOL** [FKint/JokkebrokAdministratie#37]
Implementatie van #2 
"Een hard rule verbiedt om een voogd te creëren met een identieke voornaam+naam als een reeds bestaande voogd."

1. Ik voeg een nieuwe voogd toe die matcht (voornaam, achternaam) met een bestaande voogd:
![image](https://cloud.githubusercontent.com/assets/1383142/6426541/95ad9d3c-bf60-11e4-88b3-26e8afe42e50.png)

2. Ik klik op 'OK', en de voogd wordt gecreëerd:
![image](https://cloud.githubusercontent.com/assets/1383142/6426542/c2c1a7fa-bf60-11e4-9cad-6f6ece37d70a.png)

Ik zou de override niet toestaan. Bij een match van voornaam+achternaam, komt er een waarschuwing modal waarbij aangegeven wordt dat de voogd al bestaat. Men moet de bestaande voogd opzoeken, of de naam wijzigen.

**Comment by FKint** [comment]
e2536ebda4bfb577b8c1979d06cd2cabe0e6652f
