### ISSUE TITLE
Uitstappen-view: GUI suggestions

### ISSUE THREAD

**Issue by jokkebrok** [FKint/JokkebrokAdministratie#6]
Suggestie 1
Lijst onder "Uitstapoverzicht": Paginering voorzien.
Zeer low-priority aangezien het aantal uitstappen < 10 zal zijn.

EDIT: gesplitst naar #8

**Comment by FKint** [comment]
Is deze functionaliteit nog steeds gewenst? En indien dat het geval is: linkertabel per x (bv. 10) laten verspringen zonder pagina te herladen?

**Comment by FKint** [comment]
cfc5662154382fc4df1b3c2fbd2ab095cc17d157
